### ISSUE TITLE
Clear selection button usable when disabled

### ISSUE THREAD

**Issue by ChristopherJennings** [kontent-ai/custom-element-commercetools#2]
### Brief bug description

When the content item with a selected product is published and the element is disabled, it is still possible to see and click the button to clear the product selection.

### Repro steps

1. Open a content item with a product selection and no draft
2. Observe that the clear button is visible and clickable

### Expected behavior

The  clear button is not visible

**Comment by JiriLojda** [comment]
Fixed by #44
